---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes
  tags: base-config
  
- name: add new repo
    src: repos_template.j2
    dest: /etc/yum.repos.d/homework.repo
  tags: base-config

- name: enable repos
  rhsm_repository:
    name: rhel-7-server-rpms
  tags: base-config
 
#- name: install base tools and packages

